services:
  # Backend API Service
  - type: web
    name: printsoft-erp-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
        # Will be set manually with your existing database URL

  # Frontend Static Site
  - type: web
    name: printsoft-erp-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    buildFilter:
      paths:
        - frontend/**
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: printsoft-erp-backend
          envVarKey: RENDER_EXTERNAL_URL

# Note: Database removed from Blueprint due to free tier limit
# You'll need to either:
# 1. Use your existing database connection string
# 2. Create a new database manually after deployment
