services:
  # Backend API Service
  - type: web
    name: printsoft-erp-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: printsoft-erp-db
          property: connectionString

  # Frontend Static Site
  - type: static
    name: printsoft-erp-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishPath: frontend/dist
    buildFilter:
      paths:
        - frontend/**
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: printsoft-erp-backend
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: printsoft-erp-db
    databaseName: printsoft_erp
    user: erp_user
    region: oregon
    plan: free
