
import { BaseDocument } from '@/types/businessDocuments';

export const generateVendorCustomerSection = (document: BaseDocument, documentType: string) => {
  let section = '';
  
  if (documentType === 'purchase-order' && (document as any).vendor) {
    const vendor = (document as any).vendor;
    section = `
      <div style="margin-bottom: 20px;">
        <div style="background-color: #f7fafc; padding: 8px 12px; border: 1px solid #e2e8f0; font-weight: bold; font-size: 12px; color: #2d3748;">
          Vendor Information
        </div>
        <div style="padding: 12px; border: 1px solid #e2e8f0; border-top: none; font-size: 11px; background: white; line-height: 1.4;">
          <div style="font-weight: bold; margin-bottom: 6px; color: #2d3748;">${vendor.name}</div>
          <div>${vendor.address}</div>
          <div>${vendor.city}, ${vendor.state} ${vendor.zip}</div>
          ${vendor.phone ? `<div>Phone: ${vendor.phone}</div>` : ''}
          ${vendor.email ? `<div>Email: ${vendor.email}</div>` : ''}
        </div>
      </div>
    `;
  } else if (['invoice', 'quote', 'sales-order'].includes(documentType) && (document as any).customer) {
    const customer = (document as any).customer;
    section = `
      <div style="margin-bottom: 20px;">
        <div style="background-color: #f7fafc; padding: 8px 12px; border: 1px solid #e2e8f0; font-weight: bold; font-size: 12px; color: #2d3748;">
          Customer Information
        </div>
        <div style="padding: 12px; border: 1px solid #e2e8f0; border-top: none; font-size: 11px; background: white; line-height: 1.4;">
          <div style="font-weight: bold; margin-bottom: 6px; color: #2d3748;">${customer.name}</div>
          <div>${customer.address}</div>
          <div>${customer.city}, ${customer.state} ${customer.zip}</div>
          ${customer.phone ? `<div>Phone: ${customer.phone}</div>` : ''}
          ${customer.email ? `<div>Email: ${customer.email}</div>` : ''}
        </div>
      </div>
    `;
  }
  
  return section;
};

export const generateItemsTable = (document: BaseDocument, documentType: string, currencySymbol: string) => {
  if (['payment-receipt', 'financial-report', 'delivery-note'].includes(documentType)) {
    return '';
  }

  const itemRows = document.items.map((item, index) => `
    <tr style="${index % 2 === 1 ? 'background-color: #f7fafc;' : ''}">
      <td style="padding: 8px; border: 1px solid #cbd5e0; font-size: 10px; vertical-align: top;">
        <div style="font-weight: bold; color: #2d3748; margin-bottom: 2px;">${item.itemCode}</div>
        <div style="color: #4a5568; font-size: 9px;">${item.description}</div>
      </td>
      <td style="padding: 8px; border: 1px solid #cbd5e0; font-size: 10px; text-align: center; vertical-align: top;">
        ${item.quantity}
      </td>
      <td style="padding: 8px; border: 1px solid #cbd5e0; font-size: 10px; text-align: right; vertical-align: top;">
        ${currencySymbol} ${item.unitPrice.toFixed(2)}
      </td>
      <td style="padding: 8px; border: 1px solid #cbd5e0; font-size: 10px; text-align: right; vertical-align: top;">
        ${currencySymbol} ${item.total.toFixed(2)}
      </td>
    </tr>
  `).join('');

  return `
    <table style="width: 100%; border-collapse: collapse; margin: 20px 0; border: 2px solid #2d3748;">
      <thead>
        <tr>
          <th style="background-color: #4a5568; color: white; padding: 10px 8px; text-align: left; font-size: 11px; font-weight: bold; border: 1px solid #2d3748; width: 45%;">Item Description</th>
          <th style="background-color: #4a5568; color: white; padding: 10px 8px; text-align: center; font-size: 11px; font-weight: bold; border: 1px solid #2d3748; width: 12%;">Quantity</th>
          <th style="background-color: #4a5568; color: white; padding: 10px 8px; text-align: right; font-size: 11px; font-weight: bold; border: 1px solid #2d3748; width: 18%;">Unit Price</th>
          <th style="background-color: #4a5568; color: white; padding: 10px 8px; text-align: right; font-size: 11px; font-weight: bold; border: 1px solid #2d3748; width: 25%;">Total</th>
        </tr>
      </thead>
      <tbody>
        ${itemRows}
      </tbody>
    </table>
  `;
};

export const generateFooter = (document: BaseDocument) => {
  return `
    <!-- Footer -->
    <div style="margin-top: 40px; text-align: center; padding-top: 12px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #718096;">
      <p>Generated by Priority ERP - ${new Date().toLocaleDateString('en-GB')}</p>
      <p>www.prioritysolutions.com</p>
    </div>
  `;
};
